1_2_withcode
BelkovskiDaniil/FIVT_1_semester_3_task pull request #7
Opened 2022-12-26 13:36 UTC by BelkovskiDaniil

2022-12-28 06:08 UTC, smatskevich requested changes

2022-12-28 06:08 UTC, smatskevich commented on main.cpp
> + * Рекурсия запрещена. */
Рекурсия в деструкторе Node. Напишите нерекурсивное разрушение дерева.

2022-12-28 13:36 UTC, BelkovskiDaniil commented on main.cpp
> + * Рекурсия запрещена. */
Исправил

2022-12-28 21:33 UTC, smatskevich requested changes

2022-12-28 21:33 UTC, smatskevich commented on main.cpp
> +                local->Data = 0;
Data можно не обнулять.

2022-12-28 21:33 UTC, smatskevich commented on main.cpp
> +            }
Не хватает собственно вызова delete.

2022-12-28 21:33 UTC, smatskevich commented on main.cpp
>  };
Добавьте актуальную ссылку на посылку.

2022-12-30 11:57 UTC, smatskevich requested changes

2022-12-30 11:57 UTC, smatskevich commented on main.cpp
> +            }
По-прежнему не хватает delete. Деструктор Tree вызывает этот деструктор Node для корня, но все дочерние узлы не разрушаются.

2023-02-05 13:04 UTC, smatskevich requested changes

2023-02-05 13:04 UTC, smatskevich commented on main.cpp
> +            }
Внутри этой функции должны быть вызовы delete – для дочерних узлов.

2023-02-05 13:07 UTC, smatskevich requested changes

2023-02-05 13:07 UTC, smatskevich commented on main.cpp
> +    tree.Tree::~Tree();
Это не нужно. Деструктор tree и так вызовется.

2023-03-12 17:06 UTC, closed without merging